/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _layoutRouteImport } from './routes/__layout'
import { Route as _documentationRouteImport } from './routes/__documentation'
import { Route as _adminRouteImport } from './routes/__admin'
import { Route as _layoutIndexRouteImport } from './routes/__layout/index'
import { Route as _layoutTermsOfServiceRouteImport } from './routes/__layout/terms-of-service'
import { Route as _layoutSupportRouteImport } from './routes/__layout/support'
import { Route as _layoutPrivacyPolicyRouteImport } from './routes/__layout/privacy-policy'
import { Route as _layoutLoginRouteImport } from './routes/__layout/login'
import { Route as _layoutBlogsIndexRouteImport } from './routes/__layout/blogs/index'
import { Route as _documentationDocsIndexRouteImport } from './routes/__documentation/docs/index'
import { Route as _layoutBlogsSlugRouteImport } from './routes/__layout/blogs/$slug'
import { Route as _documentationDocsPageRouteImport } from './routes/__documentation/docs/$page'
import { Route as _adminPostBuilderIdRouteImport } from './routes/__admin/post-builder.$id'

const _layoutRoute = _layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => rootRouteImport,
} as any)
const _documentationRoute = _documentationRouteImport.update({
  id: '/__documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const _adminRoute = _adminRouteImport.update({
  id: '/__admin',
  getParentRoute: () => rootRouteImport,
} as any)
const _layoutIndexRoute = _layoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutTermsOfServiceRoute = _layoutTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutSupportRoute = _layoutSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutPrivacyPolicyRoute = _layoutPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutLoginRoute = _layoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutBlogsIndexRoute = _layoutBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => _layoutRoute,
} as any)
const _documentationDocsIndexRoute = _documentationDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => _documentationRoute,
} as any)
const _layoutBlogsSlugRoute = _layoutBlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => _layoutRoute,
} as any)
const _documentationDocsPageRoute = _documentationDocsPageRouteImport.update({
  id: '/docs/$page',
  path: '/docs/$page',
  getParentRoute: () => _documentationRoute,
} as any)
const _adminPostBuilderIdRoute = _adminPostBuilderIdRouteImport.update({
  id: '/post-builder/$id',
  path: '/post-builder/$id',
  getParentRoute: () => _adminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof _layoutLoginRoute
  '/privacy-policy': typeof _layoutPrivacyPolicyRoute
  '/support': typeof _layoutSupportRoute
  '/terms-of-service': typeof _layoutTermsOfServiceRoute
  '/': typeof _layoutIndexRoute
  '/post-builder/$id': typeof _adminPostBuilderIdRoute
  '/docs/$page': typeof _documentationDocsPageRoute
  '/blogs/$slug': typeof _layoutBlogsSlugRoute
  '/docs': typeof _documentationDocsIndexRoute
  '/blogs': typeof _layoutBlogsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof _layoutLoginRoute
  '/privacy-policy': typeof _layoutPrivacyPolicyRoute
  '/support': typeof _layoutSupportRoute
  '/terms-of-service': typeof _layoutTermsOfServiceRoute
  '/': typeof _layoutIndexRoute
  '/post-builder/$id': typeof _adminPostBuilderIdRoute
  '/docs/$page': typeof _documentationDocsPageRoute
  '/blogs/$slug': typeof _layoutBlogsSlugRoute
  '/docs': typeof _documentationDocsIndexRoute
  '/blogs': typeof _layoutBlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__admin': typeof _adminRouteWithChildren
  '/__documentation': typeof _documentationRouteWithChildren
  '/__layout': typeof _layoutRouteWithChildren
  '/__layout/login': typeof _layoutLoginRoute
  '/__layout/privacy-policy': typeof _layoutPrivacyPolicyRoute
  '/__layout/support': typeof _layoutSupportRoute
  '/__layout/terms-of-service': typeof _layoutTermsOfServiceRoute
  '/__layout/': typeof _layoutIndexRoute
  '/__admin/post-builder/$id': typeof _adminPostBuilderIdRoute
  '/__documentation/docs/$page': typeof _documentationDocsPageRoute
  '/__layout/blogs/$slug': typeof _layoutBlogsSlugRoute
  '/__documentation/docs/': typeof _documentationDocsIndexRoute
  '/__layout/blogs/': typeof _layoutBlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/privacy-policy'
    | '/support'
    | '/terms-of-service'
    | '/'
    | '/post-builder/$id'
    | '/docs/$page'
    | '/blogs/$slug'
    | '/docs'
    | '/blogs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/privacy-policy'
    | '/support'
    | '/terms-of-service'
    | '/'
    | '/post-builder/$id'
    | '/docs/$page'
    | '/blogs/$slug'
    | '/docs'
    | '/blogs'
  id:
    | '__root__'
    | '/__admin'
    | '/__documentation'
    | '/__layout'
    | '/__layout/login'
    | '/__layout/privacy-policy'
    | '/__layout/support'
    | '/__layout/terms-of-service'
    | '/__layout/'
    | '/__admin/post-builder/$id'
    | '/__documentation/docs/$page'
    | '/__layout/blogs/$slug'
    | '/__documentation/docs/'
    | '/__layout/blogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _adminRoute: typeof _adminRouteWithChildren
  _documentationRoute: typeof _documentationRouteWithChildren
  _layoutRoute: typeof _layoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__layout': {
      id: '/__layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__documentation': {
      id: '/__documentation'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _documentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__admin': {
      id: '/__admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _adminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__layout/': {
      id: '/__layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _layoutIndexRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/terms-of-service': {
      id: '/__layout/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof _layoutTermsOfServiceRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/support': {
      id: '/__layout/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof _layoutSupportRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/privacy-policy': {
      id: '/__layout/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof _layoutPrivacyPolicyRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/login': {
      id: '/__layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof _layoutLoginRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/blogs/': {
      id: '/__layout/blogs/'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof _layoutBlogsIndexRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__documentation/docs/': {
      id: '/__documentation/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof _documentationDocsIndexRouteImport
      parentRoute: typeof _documentationRoute
    }
    '/__layout/blogs/$slug': {
      id: '/__layout/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof _layoutBlogsSlugRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__documentation/docs/$page': {
      id: '/__documentation/docs/$page'
      path: '/docs/$page'
      fullPath: '/docs/$page'
      preLoaderRoute: typeof _documentationDocsPageRouteImport
      parentRoute: typeof _documentationRoute
    }
    '/__admin/post-builder/$id': {
      id: '/__admin/post-builder/$id'
      path: '/post-builder/$id'
      fullPath: '/post-builder/$id'
      preLoaderRoute: typeof _adminPostBuilderIdRouteImport
      parentRoute: typeof _adminRoute
    }
  }
}

interface _adminRouteChildren {
  _adminPostBuilderIdRoute: typeof _adminPostBuilderIdRoute
}

const _adminRouteChildren: _adminRouteChildren = {
  _adminPostBuilderIdRoute: _adminPostBuilderIdRoute,
}

const _adminRouteWithChildren =
  _adminRoute._addFileChildren(_adminRouteChildren)

interface _documentationRouteChildren {
  _documentationDocsPageRoute: typeof _documentationDocsPageRoute
  _documentationDocsIndexRoute: typeof _documentationDocsIndexRoute
}

const _documentationRouteChildren: _documentationRouteChildren = {
  _documentationDocsPageRoute: _documentationDocsPageRoute,
  _documentationDocsIndexRoute: _documentationDocsIndexRoute,
}

const _documentationRouteWithChildren = _documentationRoute._addFileChildren(
  _documentationRouteChildren,
)

interface _layoutRouteChildren {
  _layoutLoginRoute: typeof _layoutLoginRoute
  _layoutPrivacyPolicyRoute: typeof _layoutPrivacyPolicyRoute
  _layoutSupportRoute: typeof _layoutSupportRoute
  _layoutTermsOfServiceRoute: typeof _layoutTermsOfServiceRoute
  _layoutIndexRoute: typeof _layoutIndexRoute
  _layoutBlogsSlugRoute: typeof _layoutBlogsSlugRoute
  _layoutBlogsIndexRoute: typeof _layoutBlogsIndexRoute
}

const _layoutRouteChildren: _layoutRouteChildren = {
  _layoutLoginRoute: _layoutLoginRoute,
  _layoutPrivacyPolicyRoute: _layoutPrivacyPolicyRoute,
  _layoutSupportRoute: _layoutSupportRoute,
  _layoutTermsOfServiceRoute: _layoutTermsOfServiceRoute,
  _layoutIndexRoute: _layoutIndexRoute,
  _layoutBlogsSlugRoute: _layoutBlogsSlugRoute,
  _layoutBlogsIndexRoute: _layoutBlogsIndexRoute,
}

const _layoutRouteWithChildren =
  _layoutRoute._addFileChildren(_layoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  _adminRoute: _adminRouteWithChildren,
  _documentationRoute: _documentationRouteWithChildren,
  _layoutRoute: _layoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
